controller_manager:
  ros__parameters:
    update_rate: 1000
    use_sim_time: true

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - RL-1-1
      - RL-1-2
      - RL-1-3
      - RL-2-1
      - RL-2-2
      - RL-2-3
      - RL-3-1
      - RL-3-2
      - RL-3-3
      - LL-1-1
      - LL-1-2
      - LL-1-3
      - LL-2-1
      - LL-2-2
      - LL-2-3
      - LL-3-1
      - LL-3-2
      - LL-3-3
    gains:
      RL-1-1: {p: 50, d: 0.5, i: 1, i_clamp: 1}
      RL-1-2: {p: 50, d: 0.5, i: 1, i_clamp: 1}
      RL-1-3: {p: 50, d: 0.5, i: 1, i_clamp: 1}
      RL-2-1: {p: 50, d: 0.5, i: 1, i_clamp: 1}
      RL-2-2: {p: 50, d: 0.5, i: 1, i_clamp: 1}
      RL-2-3: {p: 50, d: 0.5, i: 1, i_clamp: 1}
      RL-3-1: {p: 50, d: 0.5, i: 1, i_clamp: 1}
      RL-3-2: {p: 50, d: 0.5, i: 1, i_clamp: 1}
      RL-3-3: {p: 50, d: 0.5, i: 1, i_clamp: 1}
      LL-1-1: {p: 50, d: 0.5, i: 1, i_clamp: 1}
      LL-1-2: {p: 50, d: 0.5, i: 1, i_clamp: 1}
      LL-1-3: {p: 50, d: 0.5, i: 1, i_clamp: 1}
      LL-2-1: {p: 50, d: 0.5, i: 1, i_clamp: 1}
      LL-2-2: {p: 50, d: 0.5, i: 1, i_clamp: 1}
      LL-2-3: {p: 50, d: 0.5, i: 1, i_clamp: 1}
      LL-3-1: {p: 50, d: 0.5, i: 1, i_clamp: 1}
      LL-3-2: {p: 50, d: 0.5, i: 1, i_clamp: 1}
      LL-3-3: {p: 50, d: 0.5, i: 1, i_clamp: 1}
    publish_rate: 1000.0
    allow_partial_joints_goal: false


joint_state_broadcaster:
  ros__parameters:
    publish_rate: 1000.0