controller_server:
  ros__parameters:
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"  # Исправлено название
      desired_linear_vel: 0.1
      max_angular_vel: 0.1745
      rotate_to_heading_angular_vel: 0.1745
      min_approach_linear_velocity: 0.05
      use_rotate_to_heading: true

planner_server:
  ros__parameters:
    expected_planner_frequency: 1.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"

bt_navigator:
  ros__parameters:
    default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"
    plugin_lib_names:
      - "nav2_compute_path_to_pose_action_bt_node"
      - "nav2_follow_path_action_bt_node"
      - "nav2_back_up_action_bt_node"
      - "nav2_spin_action_bt_node"
      - "nav2_wait_action_bt_node"
      - "nav2_clear_costmap_service_bt_node"
      - "nav2_reinitialize_global_localization_service_bt_node"
      - "nav2_goal_reached_condition_bt_node"
      - "nav2_goal_updated_condition_bt_node"
      - "nav2_initial_pose_received_condition_bt_node"
      - "nav2_is_stuck_condition_bt_node"
      - "nav2_transform_available_condition_bt_node"
      - "nav2_time_expired_condition_bt_node"
      - "nav2_distance_traveled_condition_bt_node"
      - "nav2_rate_controller_bt_node"
      - "nav2_distance_controller_bt_node"
      - "nav2_speed_controller_bt_node"
      - "nav2_truncate_path_action_bt_node"
      - "nav2_round_robin_node_bt_node"
      - "nav2_pipeline_sequence_bt_node"
      - "nav2_recovery_node_bt_node"  # Критически важный для RecoveryNode

global_costmap:
  ros__parameters:
    update_frequency: 1.0
    publish_frequency: 1.0
    always_send_full_costmap: true
    plugins: ["static_layer", "inflation_layer"]
    static_layer:
      plugin: "nav2_costmap_2d::StaticLayer"
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"

local_costmap:
  ros__parameters:
    update_frequency: 5.0
    publish_frequency: 2.0
    plugins: ["obstacle_layer", "inflation_layer"]
    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      observation_sources: "scan"
      scan:
        topic: "/scan"
        data_type: "LaserScan"
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"